### ISSUE TITLE
Question about 'class_means'

### ISSUE THREAD

**Issue by cxy1996** [hshustc/CVPR19_Incremental_Learning#5]
Hello, Thank you for your work.

 [cifar100-class-incremental/class_incremental_cosine_cifar100.py](https://github.com/hshustc/CVPR19_Incremental_Learning/blob/master/cifar100-class-incremental/class_incremental_cosine_cifar100.py) mentioned that the `class_means[:,current_cl[iter_dico],0]` is for iCaRL (mean of exemplars) and `class_means[:,current_cl[iter_dico],1]` is for NCM (theoretical mean). 

But in [cifar100-class-incremental/eval_cumul_acc.py](https://github.com/hshustc/CVPR19_Incremental_Learning/blob/master/cifar100-class-incremental/eval_cumul_acc.py), you use the  `class_means[:,current_cl[iter_dico],1]` as the final result of your method, does it mean that you use all the historical exemplars to calculate the mean of the classes?

**Comment by wonda** [comment]
Hello, I think there is no problem. All the class means are calculated and saved for the evaluation of iCaRL and NCM classifier. But the evaluation of the "CNN acc" (the proposed method) does not use the class means.

**Comment by cxy1996** [comment]
Yes, you're right.  I misunderstood NCM.
